create file
HatsulaSeveryn/Goit_PythonCore_Team9 pull request #1
Opened 2022-11-10 18:21 UTC by IrinaShushkevych

2022-11-11 14:14 UTC, HatsulaSeveryn requested changes

2022-11-11 14:14 UTC, HatsulaSeveryn commented on classes/file_sorting.py
> +    def check_path(dir_path):
from pathlib import Path
path = Path('/etc')
path.exists(), path.is_dir(), path.is_file() -> return True/False

2022-11-11 14:14 UTC, HatsulaSeveryn commented on classes/file_sorting.py
> +        lists_free_dir = (
path.name in types.keys()

2022-11-11 14:14 UTC, HatsulaSeveryn commented on classes/file_sorting.py
> +        file_name_arr = file.split('.')
path.suffix

2022-11-11 14:14 UTC, HatsulaSeveryn commented on classes/file_sorting.py
> +            elif (ord('A') <= ord(el) <= ord('Z')) or (ord('a') <= ord(el) <= ord('z')) or el.isdigit():
el.isalnum()

2022-11-12 14:06 UTC, HatsulaSeveryn commented on classes/file_sorting.py
> +    def read_folder(self, name_folder=None):
(self, name_folder = self.name_folder):
return os.listdir(name_folder)

2022-11-12 14:19 UTC, HatsulaSeveryn commented on classes/file_sorting.py
> +    def sorting_folder(self, name_folder=None):
(self, name_folder = self.name_folder):

2022-11-12 14:22 UTC, HatsulaSeveryn commented on classes/file_sorting.py
> +    def check_clear_folder(self, name_folder=None):
(self, name_folder = self.name_folder):

2022-11-12 14:23 UTC, IrinaShushkevych commented on classes/file_sorting.py
> +    def read_folder(self, name_folder=None):
В параметрах функції не можна використовувати self, він рахується не визначенним

2022-11-12 14:24 UTC, IrinaShushkevych commented on classes/file_sorting.py
> +    def sorting_folder(self, name_folder=None):
В параметрах функції не можна використовувати self, він рахується не визначенним. Програма не компілюється, вказує що це помилка

2022-11-12 15:30 UTC, HatsulaSeveryn approved these changes, later dismissed

2022-11-12 15:37 UTC, HatsulaSeveryn approved these changes

2022-11-12 15:38 UTC, HatsulaSeveryn approved these changes

2022-11-12 15:38 UTC, HatsulaSeveryn approved these changes

2022-11-12 15:39 UTC, merged